apiVersion: v1
kind: Secret
metadata:
  name: wanderlust-secrets
  namespace: wanderlust
type: Opaque
data:
  MONGO_INITDB_ROOT_USERNAME: bW9uZ29hZG1pbg==  # base64 of 'mongoadmin'
  MONGO_INITDB_ROOT_PASSWORD: c2VjdXJlUGFzcw==  # base64 of 'securePass'
  REDIS_PASSWORD: cmVkaXNQYXNz         # base64 of 'redisPass'

