apiVersion: v1
kind: Secret
metadata:
  name: wanderlust-secrets
  namespace: wanderlust
type: Opaque
data:
  MONGO_INITDB_ROOT_USERNAME: bW9uZ29hZG1pbg==
  MONGO_INITDB_ROOT_PASSWORD: c2VjdXJlUGFzcw==
  REDIS_PASSWORD: cmVkaXNQYXNz
  MONGODB_URI: bW9uZ29kYjovL21vbmdvYWRtaW46c2VjdXJlUGFzc0Btb25nby1zZXJ2aWNlOjI3MDE3L3dhbmRlcmx1c3Q/YXV0aFNvdXJjZT1hZG1pbg==

